# Generated by Django 3.2.8 on 2021-11-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='timeLimit',
            field=models.IntegerField(default=0),
        ),
    ]
