# Generated by Django 3.2.8 on 2021-11-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0002_alter_problems_timelimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='timeLimit',
        ),
    ]
