# Generated by Django 3.2.8 on 2021-10-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0002_newmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='expected_output',
        ),
    ]
