# Generated by Django 3.2.8 on 2021-10-31 06:23

import Interface.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0003_remove_problems_expected_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='expected_output',
            field=models.FileField(default='', upload_to=Interface.models.Problems.upload_path, verbose_name='Expected Answer (txt)'),
        ),
    ]
