# Generated by Django 3.2.8 on 2021-11-17 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Interface', '0003_remove_problems_timelimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems_solved', models.IntegerField(default=0, verbose_name='solved problems')),
                ('seconds_taken', models.FloatField(default=0.0, verbose_name='seconds taken')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_leaderboard', to='Interface.problems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
