# Generated by Django 3.2.8 on 2021-10-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0004_problems_expected_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='function_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
