# Generated by Django 3.2.8 on 2021-11-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0005_alter_event_timelimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='problem',
        ),
    ]
