# Generated by Django 3.2.8 on 2021-10-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0005_problems_function_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='function_name',
        ),
    ]
