# Generated by Django 3.2.8 on 2021-11-18 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0006_remove_leaderboard_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event_board', to='Interface.event'),
        ),
    ]
