# Generated by Django 3.2.8 on 2021-11-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0007_leaderboard_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='executionTime',
            field=models.FloatField(default=0.0, verbose_name='Execution time'),
        ),
    ]
